modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/McJtyLib/blob/1.21_neo/LICENSE"
issueTrackerURL="http://github.com/McJtyMods/McJtyLib/issues"
displayURL="http://github.com/McJtyMods/McJtyLib/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="mcjtylib"
version="${file.jarVersion}"
displayName="McJtyLib"
#updateJSONURL="http://myurl.me/" #optional
description='''
Base mod for all McJty mods
'''
[[dependencies.mcjtylib]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
